### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arthurvr** [diessica/awesome-sketch#1]
This repo seems to miss a license. You could use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by diessica** [comment]
That's true! I'm gonna take a look at it.

Thank you very much.

**Comment by diessica** [comment]
License added. Refer to [last commit](https://github.com/diessica/awesome-sketch/commit/6d8cbcd38690874c596079ccac121bd08a3b5a20).
