### ISSUE TITLE
Add Service section

### ISSUE THREAD

**Issue by diessica** [diessica/awesome-sketch#3]
There are a lot of freemium services related to Sketch 3 available, like [Zeplin](https://zeplin.io/).

I'm considering adding a "Service" section.

**Comment by luandro** [comment]
I guess you could also add [Easy Share](http://easier.cc/), [Marvel](https://marvelapp.com/) and some other services that have plugins for Sketch.

**Comment by diessica** [comment]
Yeah. But they are mostly freemium services, so I'm not sure.

**Comment by luandro** [comment]
But they're still very useful. I personally use the free version of Marvel with the Sketch plugin for all my projects.

**Comment by diessica** [comment]
Thank you. I'm closing this issue since I've added the section.
