### ISSUE TITLE
Add Template and Ui Kit sections

### ISSUE THREAD

**Issue by luandro** [diessica/awesome-sketch#5]
Could be useful to have sections for Templates and Ui Kits, since there's a bunch of them it would be nice to have a selection on the most useful.

I've created a [Responsive Web Design Template](https://github.com/luandro/sketch-responsive-design-template), which could go into the template section.

**Comment by diessica** [comment]
Well-minded! I'll make it as soon as possible, though it'd be awesome if you could create a PR.

Thank you!
